[program:horizon]
process_name=LaravelHorizonQueues
priority=300
command=/opt/php83/bin/php /var/www/marriator/data/www/preprod.marriator-api.fivecorners.ru/artisan horizon
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/www/marriator/data/www/preprod.marriator-api.fivecorners.ru/storage/logs/horizon.log
stdout_logfile_maxbytes=0
stopwaitsecs=3600
